# Use the official Node.js image as the base image
FROM node:22 AS builder

ARG IMAGE_TAG
ARG REACT_PORT
ENV IMAGE_TAG=${IMAGE_TAG}
ENV REACT_PORT=${REACT_PORT}

COPY frontend/package*.json /srv/frontend-${IMAGE_TAG}/

WORKDIR /srv/frontend-${IMAGE_TAG}

RUN npm install

# Copy the rest of the application code
COPY frontend/ /srv/frontend-${IMAGE_TAG}

RUN npm run build

EXPOSE ${REACT_PORT}

CMD npm run preview -- --host