services:
  simulator_iec104_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.local
    container_name: iec104_backend_simulator
    hostname: iec104_backend_simulator
    ports:
      - "2404:2404"
      - "6006:6006"
    # networks:
    #   - app-tier  
    env_file:
      - ./backend/.env
    environment:
      - REACT_HOST=0.0.0.0
      - REACT_PORT=4051
      - FASTAPI_HOST=0.0.0.0
      - FASTAPI_PORT=6006
      - IEC_1004_SERVER_PORT=2404
  simulator_iec104_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
    container_name: iec104_frontend_simulator
    hostname: iec104_frontend_simulator
    ports:
      - "4051:4051"
    # networks:
    #   - app-tier
    env_file:
      - ./frontend/.env
    environment:
      - PORT=4051
      - FASTAPI_HOST=localhost # Ip address of the backend server
      - FASTAPI_PORT=6006